

nu =  int(input('Digite um número para ver sua tabuada:'))
print('-'*12)
print(nu,' x 1 =',nu*1)
print(nu,' x 2 =',nu*2)
print(nu,' x 3 =',nu*3)
print(nu,' x 4 =',nu*4)
print(nu,' x 5 =',nu*5)
print(nu,' x 6 =',nu*6)
print(nu,' x 7 =',nu*7)
print(nu,' x 8 =',nu*8)
print(nu,' x 9 =',nu*9)
print(nu,'x 10 =',nu*10)
print('-'*12)